import { useEffect, useState } from 'react'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowRight, Award, Building2, CalendarDays, ChefHat, ChevronDown, Clock3, Globe2, Heart, Landmark, Mail, MapPin, Menu as MenuIcon, Phone, Quote, Star, TrendingUp, Users, Utensils, X } from 'lucide-react'
import { FaFacebookF, FaInstagram, FaWhatsapp, FaYoutube } from 'react-icons/fa6'
import './App.css'

const WA = '919999999999'
const phone = '+91 99999 99999'
const branches = [
  { slug: 'sama', name: 'Sama', capacity: '130+', address: 'Sama-Savli Road, Vadodara', tag: 'Family flagship', wa: '919999999991' },
  { slug: 'bhayli', name: 'Bhayli (Vasna)', capacity: '120+', address: 'Vasna-Bhayli Road, Vadodara', tag: 'Celebration favourite', wa: '919999999992' },
  { slug: 'manjalpur', name: 'Manjalpur', capacity: '100+', address: 'Manjalpur, Vadodara', tag: 'Neighbourhood dining', wa: '919999999993' },
  { slug: 'waghodia', name: 'Waghodia', capacity: '140+', address: 'Waghodia Road, Vadodara', tag: 'Grand family dining', wa: '919999999994' },
  { slug: 'bharuch', name: 'Bharuch', capacity: '150+', address: 'Bharuch, Gujarat', tag: 'Largest celebration space', wa: '919999999995' },
  { slug: 'sayajigunj', name: 'Kathiyawadi Cutting', capacity: 'QSR', address: 'Sayajigunj, Vadodara', tag: 'Tea & snacks', wa: '919999999996' },
]
const menuItems = [
  ['Kathiyawadi', 'Sev Tameta', 'Tangy tomato curry finished with crisp sev'], ['Kathiyawadi', 'Ringan No Olo', 'Fire-roasted brinjal, village-style tadka'],
  ['Kathiyawadi', 'Lasaniya Bataka', 'Potatoes with a bold garlic masala'], ['Kathiyawadi', 'Rajwadi Gathiya', 'Our rich royal-style signature'],
  ['Punjabi', 'Paneer Handi', 'Creamy, aromatic, slow-cooked paneer'], ['Punjabi', 'Kaju Curry', 'Golden cashew curry, delicately spiced'],
  ['Punjabi', 'Paneer Butter Masala', 'Classic buttery tomato gravy'], ['Chinese', 'Noodles', 'Wok-tossed vegetables and noodles'],
  ['Chinese', 'Fried Rice', 'Fragrant rice, vegetables and sauces'], ['Chinese', 'Manchurian', 'Crisp vegetable dumplings in gravy'],
  ['Breads', 'Butter Naan', 'Tandoor-baked and butter-brushed'], ['Breads', 'Garlic Naan', 'Tandoor-baked with fresh garlic'],
  ['Rotla', 'Bajri Rotla', 'Traditional pearl millet flatbread'], ['Rotla', 'Wagharelo Rotlo', 'Garlic-tempered village favourite'],
  ['Paratha', 'Lachha Paratha', 'Layered, flaky and tandoor-baked'], ['Paratha', 'Stuffed Paratha', 'Comforting seasonal filling'],
]
const whatsapp = (text, number = WA) => window.open(`https://wa.me/${number}?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer')

function ScrollTop() { const { pathname } = useLocation(); useEffect(() => window.scrollTo(0, 0), [pathname]); return null }
function Header() {
  const [open, setOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 40); onScroll(); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const close = () => setOpen(false)
  return <header className={`header ${scrolled ? 'scrolled' : ''}`}><div className="topline"><span>From Gujarat To The World</span><div className="top-contact"><a href={`tel:${phone}`}><Phone size={12}/> {phone}</a><a className="country" href="https://usa.kathiyawadivillage.com"><Globe2 size={13}/> 🇮🇳 India · 🇺🇸 USA <ChevronDown size={12}/></a></div></div><div className="nav-wrap"><Link to="/" className="brand"><img src="/images/kathiyawadi-village-logo.jpg" alt="Kathiyawadi Village"/><span><b>Kathiyawadi Village</b><small>Pure Veg · Multi Cuisine</small></span></Link><nav className={open ? 'nav open' : 'nav'}><NavLink to="/" onClick={close}>Home</NavLink><NavLink to="/about" onClick={close}>Our Story</NavLink><div className="nav-group"><button>Locations <ChevronDown/></button><div className="nav-dropdown location-dropdown">{branches.slice(0,5).map(b=><Link key={b.slug} to={`/locations/${b.slug}`} onClick={close}><MapPin/><span><b>{b.name}</b><small>{b.address}</small></span></Link>)}<Link className="dropdown-all" to="/locations" onClick={close}>View all locations <ArrowRight/></Link></div></div><NavLink to="/menu" onClick={close}>Menu</NavLink><NavLink to="/party-orders" onClick={close}>Celebrations</NavLink><div className="nav-group"><button>Partner With Us <ChevronDown/></button><div className="nav-dropdown partner-dropdown"><Link to="/franchise" onClick={close}><Building2/><span><b>Franchise</b><small>Bring the Village to your city</small></span></Link><Link to="/investors" onClick={close}><Landmark/><span><b>Investor Relations</b><small>Build the next chapter with us</small></span></Link></div></div><div className="nav-group more"><button>More <ChevronDown/></button><div className="nav-dropdown"><Link to="/careers" onClick={close}>Careers</Link><Link to="/contact" onClick={close}>Contact Us</Link></div></div><div className="mobile-nav-actions"><button onClick={() => whatsapp('Hello Kathiyawadi Village, I would like to know more.')}><FaWhatsapp/> WhatsApp Us</button><a href="/#booking" onClick={close}>Book A Table</a></div></nav><div className="nav-actions"><button className="whatsapp-btn" onClick={() => whatsapp('Hello Kathiyawadi Village, I would like to know more.')}><FaWhatsapp/> WhatsApp</button><a className="book-btn" href="/#booking">Book A Table <ArrowRight/></a></div><button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X/> : <MenuIcon/>}</button></div></header>
}
function Footer() {
  return <><section className="footer-cta"><div><span>Come hungry. Leave with a story.</span><h2>How can we welcome you?</h2></div><div><a href="/#booking"><Utensils/> Book A Table</a><Link to="/party-orders"><CalendarDays/> Plan An Event</Link><Link to="/franchise"><Building2/> Franchise With Us</Link></div></section><footer><div className="footer-main"><div className="footer-brand"><img src="/images/kathiyawadi-village-logo.jpg" alt="Kathiyawadi Village"/><p>From Gujarat To The World — serving authentic hospitality, one plate at a time.</p><div className="socials"><a aria-label="Instagram" href="https://instagram.com" target="_blank"><FaInstagram/></a><a aria-label="Facebook" href="https://facebook.com" target="_blank"><FaFacebookF/></a><a aria-label="YouTube" href="https://youtube.com" target="_blank"><FaYoutube/></a><button aria-label="WhatsApp" onClick={() => whatsapp('Hello Kathiyawadi Village, I would like to connect.')}><FaWhatsapp/></button></div></div><div className="footer-links"><h4>Explore</h4><Link to="/about">Our Story</Link><Link to="/menu">Smart Menu</Link><Link to="/locations">All Locations</Link><Link to="/careers">Careers</Link><Link to="/contact">Contact Us</Link></div><div className="footer-links"><h4>Popular Locations</h4>{branches.slice(0,5).map(b=><a href={`https://maps.google.com/?q=${encodeURIComponent(b.address)}`} target="_blank" key={b.slug}>{b.name} <ArrowRight/></a>)}</div><div className="footer-contact"><h4>Contact & Hours</h4><a href={`tel:${phone}`}><Phone/> <span><b>{phone}</b><small>Central reservations</small></span></a><a href="mailto:hello@kathiyawadivillage.com"><Mail/> <span><b>hello@kathiyawadivillage.com</b><small>General enquiries</small></span></a><p><Clock3/><span><b>11:00 AM – 11:00 PM</b><small>Open every day</small></span></p><p><MapPin/><span><b>Vadodara, Gujarat</b><small>Khodal Foods & Hospitality Pvt. Ltd.</small></span></p></div></div><div className="footer-bottom"><span>© 2026 Khodal Foods & Hospitality Pvt. Ltd.</span><div><a href="#">Privacy Policy</a><a href="#">Terms</a><a href="#">Refund Policy</a><a href="#">Sitemap</a></div><small>Authentic hospitality, one plate at a time.</small></div></footer><div className="mobile-bar"><a href={`tel:${phone}`}><Phone/>Call</a><Link to="/locations"><MapPin/>Directions</Link><button onClick={() => whatsapp('Hello, I would like to enquire.')}><FaWhatsapp/>WhatsApp</button><a href="/#booking"><Utensils/>Book</a></div></>
}
function SectionTitle({ eyebrow, title, text, light = false }) { return <div className={`section-title ${light ? 'light' : ''}`}><span>{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function BookingForm({ event = false }) {
  const [form, setForm] = useState({ name: '', mobile: '', location: 'Sama', date: '', time: '', guests: '', request: '', eventType: 'Birthday Party' })
  const set = e => setForm({ ...form, [e.target.name]: e.target.value })
  const submit = e => { e.preventDefault(); const branch = branches.find(b => b.name === form.location); whatsapp(`${event ? 'New Event & Catering Enquiry' : 'New Table Booking Inquiry'}\n\nName: ${form.name}\nMobile: ${form.mobile}\n${event ? `Event: ${form.eventType}\n` : ''}Branch: ${form.location}\nGuests: ${form.guests}\nDate: ${form.date}\n${event ? '' : `Time: ${form.time}\n`}Special Request: ${form.request || 'None'}`, branch?.wa) }
  return <form className="booking-form" onSubmit={submit}><label><span>Name</span><input required name="name" value={form.name} onChange={set} placeholder="Your full name"/></label><label><span>Mobile Number</span><input required name="mobile" value={form.mobile} onChange={set} placeholder="+91 98765 43210"/></label>{event && <label><span>Event Type</span><select name="eventType" value={form.eventType} onChange={set}><option>Birthday Party</option><option>Anniversary Party</option><option>Corporate Event</option><option>Wedding Catering</option><option>Outdoor Catering</option></select></label>}<label><span>Location</span><select name="location" value={form.location} onChange={set}>{branches.map(b => <option key={b.slug}>{b.name}</option>)}</select></label><label><span>Date</span><input required type="date" name="date" value={form.date} onChange={set}/></label>{!event && <label><span>Time</span><input required type="time" name="time" value={form.time} onChange={set}/></label>}<label><span>Guests</span><input required type="number" name="guests" value={form.guests} onChange={set} placeholder="e.g. 6"/></label><label className="wide"><span>Special Request</span><input name="request" value={form.request} onChange={set} placeholder="Birthday, high chair, dietary note..."/></label><button className="btn solid wide" type="submit"><FaWhatsapp/> Send on WhatsApp <ArrowRight size={17}/></button></form>
}
function Home() {
  return <main><section className="hero"><div className="hero-content"><span className="eyebrow">Pure Vegetarian · Since 2014</span><h1>Authentic Kathiyawadi <em>Hospitality.</em></h1><p>Experience Gujarat’s most loved flavours, served with warmth, tradition, and premium hospitality.</p><div className="hero-actions"><a className="btn gold" href="#booking">Book Your Table <ArrowRight size={18}/></a><Link className="btn glass" to="/locations">Explore Locations</Link></div><div className="hero-proof"><div><b>4.5+</b><span>Average Rating</span></div><div><b>10K+</b><span>Happy Families</span></div><div><b>6</b><span>Locations</span></div></div></div><div className="hero-note"><Star fill="currentColor"/><span>Made with tradition.<br/><b>Served with heart.</b></span></div></section>
  <section id="booking" className="booking-section"><div className="booking-intro"><span className="eyebrow">Your table awaits</span><h2>Reserve a memorable meal.</h2><p>Choose your nearest Kathiyawadi Village and we’ll confirm your table personally on WhatsApp.</p><div className="mini-trust"><Phone size={17}/><span>Need help? Call <b>{phone}</b></span></div></div><BookingForm/></section>
  <section className="signature"><div className="signature-image"><img src="/images/signature-feast.png" alt="Signature Kathiyawadi dishes"/><div className="dish-badge"><span>Must try</span><b>Village Feast</b></div></div><div className="signature-copy"><SectionTitle light eyebrow="Our signature dishes" title="Flavours that feel like home." text="Slow-cooked traditions, bold spices and recipes carried forward with care."/><div className="dish-list">{['Rajwadi Kaju Gathiya','Kathiyawadi Ghotalo','Garlic Wagharelo Rotlo','Ringan No Olo','Sev Tameta','Churma Ladoo'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div><Link className="text-link light" to="/menu">Explore our smart menu <ArrowRight/></Link></div></section>
  <section className="chef-section"><div className="chef-portrait"><div className="chef-icon"><ChefHat/></div><div><span>Recommended by our master chef</span><h3>A plate should nourish the heart before it reaches the table.</h3><p>Our chefs balance traditional village recipes with the refinement and consistency a modern family restaurant deserves.</p></div></div><div className="chef-menu"><span className="eyebrow">Chef’s Recommendations</span>{['Chef Special Paneer Handi','Matka Paneer','Rajwadi Kaju Curry','Kathiyawadi Special Ghotalo','Special Punjabi Combo'].map((x,i)=><div key={x}><b>{x}</b><span>{i===3?'House Signature':'Chef Special'}</span></div>)}</div></section>
  <section className="stats">{[['10,000+','Happy Customers'],['10,000+','Google Reviews'],['6+','Locations'],['4.5+','Average Rating']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</section>
  <section className="why section-pad"><SectionTitle eyebrow="The Village Promise" title="Why families choose us." text="Everything we do begins with good food and ends with genuine care."/><div className="feature-grid">{[[Heart,'Authentic Taste','Recipes rooted in Kathiyawad.'],[Award,'Pure Vegetarian','Thoughtful, trusted dining.'],[Users,'Family Friendly','Comfort for every generation.'],[MapPin,'Multiple Locations','Always close to home.'],[CalendarDays,'Party Orders','Celebrations made effortless.'],[ChefHat,'Catering Services','Hospitality wherever you are.']].map(([Icon,t,p])=><div className="feature-card" key={t}><Icon/><h3>{t}</h3><p>{p}</p></div>)}</div></section>
  <section className="story-split"><div className="story-copy"><SectionTitle eyebrow="Khodal Foods & Hospitality" title="Rooted in Gujarat. Ready for the world." text="What began as a belief in warm, honest hospitality has grown into a family of restaurant experiences trusted by thousands."/><div className="story-points"><div><b>Our Vision</b><p>To make authentic Gujarati hospitality loved across borders.</p></div><div><b>Our Mission</b><p>Consistent food, heartfelt service, and memorable spaces.</p></div></div><Link className="btn outline" to="/about">Discover Our Journey <ArrowRight size={17}/></Link></div><div className="founder-card"><Quote/><p>“Our goal is to bring authentic Kathiyawadi hospitality to every family across India and around the world.”</p><div><b>The Founder</b><span>Khodal Foods & Hospitality Pvt. Ltd.</span></div></div></section>
  <section className="events section-pad"><SectionTitle eyebrow="Real People. Real Experiences." title="Made for moments worth remembering."/><div className="event-grid">{[['Birthday Celebrations','Delicious food and memorable moments.'],['Anniversary Celebrations','Create warm memories with loved ones.'],['Corporate Gatherings','Ideal for meetings and team events.'],['Indoor & Outdoor Catering','Professional hospitality for every function.']].map((x,i)=><div className={`event-card e${i+1}`} key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div><Link className="btn solid center-btn" to="/party-orders">Plan Your Event <ArrowRight size={17}/></Link></section>
  <LocationsPreview/><Reviews/>
  <section className="opportunity"><div><span className="eyebrow">Franchise Opportunity</span><h2>Take authentic hospitality to your city.</h2><p>Join a growing restaurant brand with a proven support system, trusted recipes, operational guidance, and ambitious expansion plans.</p><Link to="/franchise" className="btn gold">Become A Franchise Partner <ArrowRight size={17}/></Link></div><div className="growth-card"><TrendingUp/><b>Built to grow, together.</b><span>Brand · Training · Operations · Marketing</span></div></section>
  <section className="investor-tease"><div><Landmark/><span>Investor Relations</span><h2>Invest in a beloved regional brand with global ambition.</h2></div><Link className="btn outline" to="/investors">Talk To Investor Relations <ArrowRight size={17}/></Link></section>
  <section className="world section-pad"><SectionTitle light eyebrow="Coming Soon" title="Expanding Across India & The World" text="From Gujarat to global neighbourhoods, our next chapter is already being written."/><div className="cities">{['Dubai','Malaysia','Singapore','Mumbai','Delhi'].map(x=><span key={x}><MapPin/> {x}</span>)}</div></section><Gallery/></main>
}
function LocationsPreview() { return <section className="locations section-pad"><div className="section-head-row"><SectionTitle eyebrow="Our Locations" title="Your nearest Village is ready." text="Six welcoming destinations. One standard of heartfelt hospitality."/><Link className="text-link" to="/locations">View all locations <ArrowRight/></Link></div><div className="location-grid">{branches.map(b=><article className="location-card" key={b.slug}><div className="location-visual"><MapPin/><span>{b.tag}</span></div><div className="location-info"><span>{b.capacity} {b.capacity !== 'QSR' && 'Guests'}</span><h3>{b.name}</h3><p>{b.address}</p><div><a href={`https://maps.google.com/?q=${encodeURIComponent(b.address)}`} target="_blank">Directions</a><Link to={`/locations/${b.slug}`}>View Branch <ArrowRight/></Link></div></div></article>)}</div></section> }
function Reviews() { return <section className="reviews section-pad"><div className="rating"><span>Google Reviews</span><strong>4.7</strong><div>★★★★★</div><p>Loved by 10,000+ guests</p></div><div className="review-list">{[['“The rotlo and olo taste wonderfully authentic. Our whole family loved the warmth of the team.”','Priya Patel'],['“Beautiful ambience, fast service and great food. Perfect for family celebrations.”','Mihir Shah'],['“One of our favourite pure veg restaurants in Vadodara. Consistent every time.”','Riya Desai']].map(x=><blockquote key={x[1]}><div>★★★★★</div><p>{x[0]}</p><cite>{x[1]} · Google Review</cite></blockquote>)}</div></section> }
function Gallery() { return <section className="gallery section-pad"><SectionTitle eyebrow="The Village Gallery" title="A glimpse of good times."/><div className="gallery-grid"><div className="g-food"><span>Food Photography</span></div><div className="g-family"><span>Customer Moments</span></div><div className="g-space"><span>Restaurant Interiors</span></div><div className="g-event"><span>Events</span></div></div></section> }
function PageHero({ eyebrow, title, text }) { return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section> }
function About() { return <main><PageHero eyebrow="Our Story" title="A village idea with a world-sized vision." text="The journey of Khodal Foods & Hospitality is a story of honest flavour, determined people, and an enduring belief in heartfelt service."/><section className="about-intro section-pad"><div><SectionTitle eyebrow="The Beginning" title="Built on food that brings people together."/><p>Founded with a simple ambition to serve authentic Kathiyawadi food in a welcoming family setting, Kathiyawadi Village grew one table, one guest, and one city at a time.</p><p>Today, our portfolio brings together the full-service Kathiyawadi Village experience and the quick, energetic Kathiyawadi Cutting tea and snacks brand.</p></div><div className="heritage-mark">ગુજરાતથી<br/><em>વિશ્વ સુધી</em><span>From Gujarat to the world</span></div></section><section className="timeline section-pad"><SectionTitle light eyebrow="Our Journey" title="Growth with gratitude."/><div>{[['2014','The first table','Our authentic hospitality journey begins.'],['2018','A family favourite','New locations welcome thousands of new guests.'],['2023','A growing portfolio','Kathiyawadi Cutting brings tea and snacks to a new format.'],['2026','India and beyond','Expansion plans take our hospitality to new cities and countries.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="values section-pad"><SectionTitle eyebrow="Vision & Mission" title="Hospitality without borders."/><div className="value-grid"><div><Globe2/><h3>Our Vision</h3><p>To become the world’s most loved ambassador of authentic Kathiyawadi hospitality.</p></div><div><Heart/><h3>Our Mission</h3><p>To give every guest generous food, thoughtful service, and a reason to return.</p></div><div><Award/><h3>Our Standard</h3><p>Pure vegetarian kitchens, consistent recipes, and excellence at every table.</p></div></div></section><section className="world section-pad"><SectionTitle light eyebrow="The Next Chapter" title="International Goals" text="Dubai, Malaysia, Singapore and the great cities of India are part of our bold next chapter."/><Link className="btn gold" to="/franchise">Grow With Us <ArrowRight/></Link></section></main> }
function Locations() { return <main><PageHero eyebrow="Find Your Village" title="Six locations. One warm welcome." text="Discover authentic Kathiyawadi food, generous spaces and memorable family dining near you."/><LocationsPreview/></main> }
function Branch() { const slug = useLocation().pathname.split('/').pop(); const b = branches.find(x => x.slug === slug) || branches[0]; return <main><PageHero eyebrow={`${b.tag} · ${b.capacity} capacity`} title={`Kathiyawadi Village ${b.name}`} text={`Perfect for family dining, birthday parties and group celebrations in ${b.name}.`}/><section className="branch-grid section-pad"><div className="branch-details"><h2>Plan your visit</h2><div><MapPin/><span><b>Address</b>{b.address}</span></div><div><Phone/><span><b>Contact</b>{phone}</span></div><div><CalendarDays/><span><b>Hours</b>11:00 AM – 11:00 PM, every day</span></div><a className="btn solid" href={`https://maps.google.com/?q=${encodeURIComponent(b.address)}`} target="_blank">Get Directions <ArrowRight/></a></div><div className="branch-feature"><img src="/images/signature-feast.png" alt="Popular dishes"/><span>Popular at {b.name}</span><h3>Village Feast & Chef Specials</h3></div></section><section className="booking-section"><div className="booking-intro"><span className="eyebrow">Reserve at {b.name}</span><h2>Your table is waiting.</h2><p>Send a booking request and our team will confirm it on WhatsApp.</p></div><BookingForm/></section><Reviews/><Gallery/></main> }
function SmartMenu() { const cats = ['All', ...new Set(menuItems.map(x => x[0]))]; const [active, setActive] = useState('All'); const shown = active === 'All' ? menuItems : menuItems.filter(x=>x[0]===active); return <main><PageHero eyebrow="Pure Veg · Multi Cuisine" title="A menu made for every mood." text="From beloved Kathiyawadi classics to Punjabi comfort and wok-tossed favourites."/><section className="menu-page section-pad"><div className="filters">{cats.map(x=><button className={active===x?'active':''} onClick={()=>setActive(x)} key={x}>{x}</button>)}</div><div className="menu-grid">{shown.map(x=><article key={x[1]}><div><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div><Star size={18}/></article>)}</div></section></main> }
function Party() { return <main><PageHero eyebrow="Celebrations & Catering" title="You celebrate. We handle the hospitality." text="From intimate birthdays to wedding catering, our team brings generous food and thoughtful service to every occasion."/><section className="services section-pad">{['Birthday Parties','Anniversary Parties','Corporate Events','Kitty Parties','Family Functions','Outdoor Catering','Wedding Catering'].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3></div>)}</section><section className="booking-section"><div className="booking-intro"><span className="eyebrow">Plan Your Event</span><h2>Tell us what you’re celebrating.</h2><p>Share your requirements and our events team will connect with you on WhatsApp.</p></div><BookingForm event/></section></main> }
function LeadForm({ type }) { const [f,setF]=useState({name:'',mobile:'',city:'',budget:'',message:''}); const change=e=>setF({...f,[e.target.name]:e.target.value}); const submit=e=>{e.preventDefault();whatsapp(`New ${type} Enquiry\n\nName: ${f.name}\nMobile: ${f.mobile}\nCity: ${f.city}\n${f.budget?`Budget: ${f.budget}\n`:''}Message: ${f.message}`)}; return <form className="lead-form" onSubmit={submit}>{['name','mobile','city'].map(x=><label key={x}><span>{x[0].toUpperCase()+x.slice(1)}</span><input required name={x} value={f[x]} onChange={change}/></label>)}{type==='Franchise'&&<label><span>Investment Budget</span><select name="budget" value={f.budget} onChange={change}><option value="">Select a range</option><option>₹50L – ₹1Cr</option><option>₹1Cr – ₹2Cr</option><option>₹2Cr+</option></select></label>}<label className="wide"><span>Message</span><textarea name="message" value={f.message} onChange={change}/></label><button className="btn solid wide">Send Enquiry on WhatsApp <ArrowRight/></button></form> }
function Franchise() { return <main><PageHero eyebrow="Franchise Opportunity" title="Bring the Village to your city." text="Build a future-ready restaurant business with a loved Gujarati hospitality brand and an experienced operating team."/><section className="franchise-metrics"><div><b>6+</b><span>Operating locations</span></div><div><b>10K+</b><span>Trusted guests</span></div><div><b>2</b><span>Scalable formats</span></div><div><b>Global</b><span>Expansion ambition</span></div></section><section className="support section-pad"><SectionTitle eyebrow="A Partnership Built To Perform" title="More than a franchise. A complete support system."/><div className="feature-grid">{['Site Selection','Restaurant Design','Kitchen & Operations','Training & Recruitment','Launch Marketing','Ongoing Growth'].map((x,i)=><div className="feature-card" key={x}><b>0{i+1}</b><h3>{x}</h3><p>Hands-on guidance from an experienced hospitality team.</p></div>)}</div></section><section className="lead-section section-pad"><SectionTitle light eyebrow="Start A Conversation" title="Become a franchise partner." text="Tell us about your city and investment plan. Our expansion team will connect with you personally."/><LeadForm type="Franchise"/></section></main> }
function Investors() { return <main><PageHero eyebrow="Investor Relations" title="Backing the future of authentic Indian hospitality." text="Khodal Foods & Hospitality is building a scalable, trusted portfolio made for India and international markets."/><section className="invest-grid section-pad">{[[Building2,'Company Overview','A growing hospitality company with two distinct restaurant formats.'],[TrendingUp,'Growth Journey','From one local idea to a multi-location, multi-brand platform.'],[Globe2,'Future Expansion','India, Dubai, Malaysia, Singapore and beyond.'],[Landmark,'Investor Benefits','A meaningful opportunity in trusted regional cuisine.']].map(([I,t,p])=><div key={t}><I/><h3>{t}</h3><p>{p}</p></div>)}</section><section className="lead-section section-pad"><SectionTitle light eyebrow="Investor Enquiry" title="Let’s build the next chapter." text="Connect directly with our investor relations team."/><LeadForm type="Investor Relations"/></section></main> }
function Careers() { return <main><PageHero eyebrow="Careers" title="Build memorable hospitality with us." text="Join a team where warm service, honest effort and growth are always on the menu."/><section className="jobs section-pad">{[['Restaurant Staff','Service associates, hosts and cashiers'],['Kitchen Team','Chefs, cooks and kitchen stewards'],['Management Team','Restaurant and area managers'],['Corporate Team','Marketing, HR, finance and expansion']].map(x=><article key={x[0]}><div><h3>{x[0]}</h3><p>{x[1]}</p></div><button className="btn outline" onClick={()=>whatsapp(`Hello, I would like to apply for the ${x[0]} at Kathiyawadi Village.`)}>Apply via WhatsApp <ArrowRight/></button></article>)}</section></main> }
function Contact() { return <main><PageHero eyebrow="Contact Us" title="We’d love to hear from you." text="Bookings, feedback, catering or partnerships — there’s always someone ready to help."/><section className="contact-grid section-pad"><div><Phone/><h3>Call Us</h3><a href={`tel:${phone}`}>{phone}</a></div><div><FaWhatsapp/><h3>WhatsApp</h3><button onClick={()=>whatsapp('Hello Kathiyawadi Village, I would like to get in touch.')}>Start a conversation</button></div><div><MapPin/><h3>Visit Us</h3><Link to="/locations">Explore all locations</Link></div><div><Globe2/><h3>Email</h3><a href="mailto:hello@kathiyawadivillage.com">hello@kathiyawadivillage.com</a></div></section></main> }
function App() { return <BrowserRouter><ScrollTop/><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/locations" element={<Locations/>}/><Route path="/locations/:slug" element={<Branch/>}/><Route path="/menu" element={<SmartMenu/>}/><Route path="/party-orders" element={<Party/>}/><Route path="/franchise" element={<Franchise/>}/><Route path="/investors" element={<Investors/>}/><Route path="/careers" element={<Careers/>}/><Route path="/contact" element={<Contact/>}/></Routes><Footer/></BrowserRouter> }
export default App
